spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
  cloud:
    gateway:
      routes:
        - id: authenticate
          uri: https://localhost:8080/
          predicates:
            - Path=/login
          filters:
            - SetPath=/authenticate

        - id: authenticate-cookie
          uri: https://localhost:8080/authenticate-cookie
          predicates:
            - Path=/login-cookie
          filters:
            - SetPath=/authenticate-cookie
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
