spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apiDB
    driverClassName: org.postgresql.Driver
    username: admin
    password: 123
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

